---
title: "Untitled"
author: "Demetri Pananos"
date: "07/12/2021"
output: pdf_document
---


```{r, include=FALSE, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(
  echo = F,
  message = F,
  warning = F,
  fig.height = 4,
  fig.align = 'center',
  dpi = 400,
  cache = T
)


library(tidyverse)
library(rstanarm)
library(tidybayes)
library(cmdstanr)
library(rms)
library(posterior)
library(rsample)
library(duckdb)
library(DBI)
source('R/utils.R')
theme_set(theme_light())

cmdstanr::register_knitr_engine(override = F)
```


```{r}
con = dbConnect(duckdb(),'data/database/apixaban_data.duckdb')
d = tbl(con, 'scaled_cleaned_data') %>% 
    collect()

dbDisconnect(con)
```


```{r}
dd = datadist(d)
options(datadist='dd')

markus_model = ols(log(yobs_ng_ml) ~ dose_mg_twice_daily + hrs_post_dose + is_male + age + weight_kg + creatinine_micromol_l + amiodarone_mg_day + diltiazem_mg_day, data = d, x=T, y=T)

extended_model = ols(log(yobs_ng_ml) ~ dose_mg_twice_daily + hrs_post_dose*(is_male + age + weight_kg + creatinine_micromol_l) + amiodarone_mg_day + diltiazem_mg_day, data = d, x=T, y=T)


validate(markus_model, B = 1000)
validate(extended_model, B = 1000)

a = exp(predict(markus_model))
b = exp(predict(extended_model))
```


# Bayesian Models

```{r}
stan_data = design_matrices(
  v.formula=~(age + weight_kg)*is_male, 
  ke.formula=~(weight_kg + creatinine_micromol_l )*is_male, 
  f.formula = ~amiodarone_mg_day + diltiazem_mg_day, 
  a.formula = ~is_male, 
  d)

model = cmdstan_model('models/005_double_exp_beta_prior.stan')
  
fit = model$sample(stan_data, parallel_chains=4)

ypred = extract_prediction(fit, 'yppc')
ytrue = d$yobs_ng_ml

MLmetrics::MSE(log(ypred), log(ytrue))
MLmetrics::R2_Score(log(ypred), log(ytrue))


plot(log(ypred), log(ytrue))
abline(0, 1, add=T)

bayesplot::mcmc_hist(fit$draws('beta_ke'))
```
